# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pPHbopC7Lt1sgbLR1BeQPAdM-_uJ32T
"""

# Part A - Section 1: Loading the Dataset


import pandas as pd

# File paths (upload these to Colab or mount Drive)
file_path_gameplay = 'User Gameplay data.xlsx'
file_path_deposit = 'Deposit Data.xlsx'
file_path_withdrawal = 'Withdrawal Data.xlsx'

# Load data with correct date format (dd-mm-yyyy)
gameplay_df = pd.read_excel(file_path_gameplay)
deposit_df = pd.read_excel(file_path_deposit)
withdrawal_df = pd.read_excel(file_path_withdrawal)

# Convert datetime with dayfirst=True
gameplay_df['Datetime'] = pd.to_datetime(gameplay_df['Datetime'], dayfirst=True)
deposit_df['Datetime'] = pd.to_datetime(deposit_df['Datetime'], dayfirst=True)
withdrawal_df['Datetime'] = pd.to_datetime(withdrawal_df['Datetime'], dayfirst=True)

# Rename for consistency
gameplay_df.rename(columns={'User ID': 'User_Id', 'Games Played': 'Games_Played'}, inplace=True)
deposit_df.rename(columns={'User Id': 'User_Id'}, inplace=True)
withdrawal_df.rename(columns={'User Id': 'User_Id'}, inplace=True)

"""Filtering data by slots"""

# Part A - Section 2: Filter Slot-wise Data for Given Dates


def filter_slot_data(df, date, slot):
    """
    Filters dataframe for a specific date and time slot.
    Slot S1 = 00:00 to 11:59
    Slot S2 = 12:00 to 23:59
    """
    date = pd.to_datetime(date).date()
    if slot == 'S1':
        start = pd.Timestamp(f"{date} 00:00:00")
        end = pd.Timestamp(f"{date} 11:59:59")
    elif slot == 'S2':
        start = pd.Timestamp(f"{date} 12:00:00")
        end = pd.Timestamp(f"{date} 23:59:59")
    else:
        raise ValueError("Invalid slot. Use 'S1' or 'S2'.")

    return df[(df['Datetime'] >= start) & (df['Datetime'] <= end)].copy()

# Slots to analyze (with correct year 2022)
slots = [
    ('2022-10-02', 'S1'),
    ('2022-10-16', 'S2'),
    ('2022-10-18', 'S1'),
    ('2022-10-26', 'S2')
]

# Store filtered slot data
slot_gameplay = {}
slot_deposit = {}
slot_withdrawal = {}

for date, slot in slots:
    key = f"{date}_Slot_{slot}"
    slot_gameplay[key] = filter_slot_data(gameplay_df, date, slot)
    slot_deposit[key] = filter_slot_data(deposit_df, date, slot)
    slot_withdrawal[key] = filter_slot_data(withdrawal_df, date, slot)

"""Calculate Loyalty Points for Each Slot"""

# Part A - Section 3: Compute Loyalty Points for Each Slot & User


def calculate_slot_loyalty_points(game_df, dep_df, wd_df):
    # Summarize deposits
    deposit_summary = dep_df.groupby('User_Id')['Amount'].agg(['count', 'sum']).reset_index()
    deposit_summary.rename(columns={'count': 'num_deposits', 'sum': 'total_deposit'}, inplace=True)

    # Summarize withdrawals
    withdrawal_summary = wd_df.groupby('User_Id')['Amount'].agg(['count', 'sum']).reset_index()
    withdrawal_summary.rename(columns={'count': 'num_withdrawals', 'sum': 'total_withdrawal'}, inplace=True)

    # Summarize games
    game_summary = game_df.groupby('User_Id')['Games_Played'].sum().reset_index()

    # Merge summaries
    merged = pd.merge(deposit_summary, withdrawal_summary, on='User_Id', how='outer')
    merged = pd.merge(merged, game_summary, on='User_Id', how='outer')
    merged.fillna(0, inplace=True)

    # Calculate loyalty
    merged['Loyalty_Points'] = (
        (0.01 * merged['total_deposit']) +
        (0.005 * merged['total_withdrawal']) +
        (0.001 * (merged['num_deposits'] - merged['num_withdrawals']).clip(lower=0)) +
        (0.2 * merged['Games_Played'])
    )

    return merged[['User_Id', 'Loyalty_Points']].sort_values(by='Loyalty_Points', ascending=False)

# Final output: results for all four requested slots
slot_loyalty_results = {}

for date, slot in slots:
    key = f"{date}_Slot_{slot}"
    result_df = calculate_slot_loyalty_points(
        slot_gameplay[key],
        slot_deposit[key],
        slot_withdrawal[key]
    )
    slot_loyalty_results[key] = result_df
    print(f"\n Loyalty Points for {key}:")
    print(result_df)



"""Monthly Loyalty Points & Leaderboard Ranking"""

# Part A - Q2: Monthly Total Loyalty Points with Ranking and Tie-Breaker


def calculate_monthly_loyalty(game_df, dep_df, wd_df):
    # Aggregate deposit info per user
    deposit_summary = dep_df.groupby('User_Id')['Amount'].agg(['count', 'sum']).reset_index()
    deposit_summary.rename(columns={'count': 'num_deposits', 'sum': 'total_deposit'}, inplace=True)

    # Aggregate withdrawal info per user
    withdrawal_summary = wd_df.groupby('User_Id')['Amount'].agg(['count', 'sum']).reset_index()
    withdrawal_summary.rename(columns={'count': 'num_withdrawals', 'sum': 'total_withdrawal'}, inplace=True)

    # Total games played per user
    game_summary = game_df.groupby('User_Id')['Games_Played'].sum().reset_index()

    # Merge all summaries
    merged = pd.merge(deposit_summary, withdrawal_summary, on='User_Id', how='outer')
    merged = pd.merge(merged, game_summary, on='User_Id', how='outer')
    merged.fillna(0, inplace=True)  # Replace missing values with 0

    # Loyalty points calculation
    merged['Loyalty_Points'] = (
        (0.01 * merged['total_deposit']) +
        (0.005 * merged['total_withdrawal']) +
        (0.001 * (merged['num_deposits'] - merged['num_withdrawals']).clip(lower=0)) +
        (0.2 * merged['Games_Played'])
    )

    # 🔐 Filter out invalid or ghost users (like 0 or NaN)
    merged = merged[merged['User_Id'] != 0]
    merged = merged[~merged['User_Id'].isna()]

    # Assign ranks: sort by Loyalty_Points, then by Games_Played as tiebreaker
    merged_sorted = merged.sort_values(
        by=['Loyalty_Points', 'Games_Played'], ascending=[False, False]
    ).reset_index(drop=True)
    merged_sorted['Rank'] = merged_sorted.index + 1

    return merged_sorted[['Rank', 'User_Id', 'Loyalty_Points', 'Games_Played']]

# Run the function and get final leaderboard
monthly_loyalty_df = calculate_monthly_loyalty(gameplay_df, deposit_df, withdrawal_df)

# ✅ Display the top 10 users (or top 50 for Part B)
print("Monthly Top 10 Loyalty Leaderboard (After Filtering):")
print(monthly_loyalty_df.head(10))

"""Q3 – Average Deposit Amount (overall)"""

# Q3 – Average Deposit Amount (overall)
avg_deposit = deposit_df['Amount'].mean()
print(f"Average deposit amount: ₹{avg_deposit:.2f}")

"""Average deposit amount per user in the month"""

avg_deposit_per_user = deposit_df.groupby('User_Id')['Amount'].sum().mean()
print(f"Average monthly deposit amount per user: ₹{avg_deposit_per_user:.2f}")

"""Average number of games played per user"""

avg_games_per_user = gameplay_df.groupby('User_Id')['Games_Played'].sum().mean()
print(f"Average number of games played per user: {avg_games_per_user:.2f}")

"""Part B – Bonus Distribution Strategy for Top 50 Players
Objective:
Distribute a total of ₹50,000 fairly among the Top 50 users

The company wants to give 50,000 as bonus to the top 50 players.
I suggest splitting the bonus in a fair way based on:
• 70% weightage to loyalty points
• 30% weightage to number of games played
This gives value both to money spent and time spent by users.
"""

# Part B - Bonus Distribution for Top 50 Players


# Select top 50 players based on final monthly loyalty leaderboard
top_50 = monthly_loyalty_df.head(50).copy()

# Normalize both Loyalty Points and Games Played
top_50['norm_loyalty'] = top_50['Loyalty_Points'] / top_50['Loyalty_Points'].sum()
top_50['norm_games'] = top_50['Games_Played'] / top_50['Games_Played'].sum()

# Weighted Score = 70% loyalty + 30% games
top_50['weighted_score'] = (0.7 * top_50['norm_loyalty']) + (0.3 * top_50['norm_games'])

# Allocate ₹50,000 based on weighted score
BONUS_POOL = 50000
top_50['Bonus_Amount'] = (top_50['weighted_score'] / top_50['weighted_score'].sum()) * BONUS_POOL

# Round to 2 decimal places
top_50['Bonus_Amount'] = top_50['Bonus_Amount'].round(2)

# Final Output
print("Bonus Distribution – Top 10 of 50 Players:")
print(top_50[['Rank', 'User_Id', 'Loyalty_Points', 'Games_Played', 'Bonus_Amount']].head(10))

